### ISSUE TITLE
ReadMe text Q on listener config

### ISSUE THREAD

**Issue by jlivingood** [Comcast/DNS-over-HTTPs-translator#2]
Per the readme - "The DoH-Translator listens on port 80..."

Is that correct? Or is it TCP/443? Or both TCP/80 and TCP/443?

**Comment by jlivingood** [comment]
NGINX on TCP/443 --> TCP/80 to translator (written in Go) --> DNS UDP/53

**Comment by tawmuz** [comment]
That's right! The translator is meant to be used with an NGINX front-end which terminates the 443 connections which forwards request to the translator’s port 80.
